packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true
patchedDependencies:
  '@vitejs/plugin-vue@6.0.9': patches/@vitejs__plugin-vue@6.0.9.patch
  astro-icon@1.2.0: patches/astro-icon@1.2.0.patch
