# available directory themes:
# spearmint, peppermint, hemingway, brookmint
theme = 'brookmint'

[general]
title = "Meditation Apps"
logo = ""
iconLogo = "tabler:coffee"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Blog"
href = "/blog"

[[header.navbar.links]]
name = "Analytics"
href = "https://us.posthog.com/shared/vHlGCcSqPjGH4r_QijaXSETtmN9J-g"
target = "_blank"

[footer]
description = "Best directory for my niche."

[footer.socials.x]
link = "https://x.com/mark_bruderer"

[footer.socials.youtube]
link = "https://www.youtube.com/@mark_hacks"
